In [1]:
import numpy as np

In [2]:
arr1=np.array([23,56,78,80,75,4])

In [4]:
arr2=np.array([[2,3,6],[6,8,9],[12,34,56]])

In [6]:
arr3=np.array([[[3,5,7],[12,34,56]],[[6,8,9],[7,3,2]]])

In [10]:
arr1.ndim,arr2.ndim,arr3.ndim

(1, 2, 3)

In [11]:
arr3

array([[[ 3,  5,  7],
        [12, 34, 56]],

       [[ 6,  8,  9],
        [ 7,  3,  2]]])

In [13]:
arr3[0,1,2]

56

In [14]:
arr4=np.random.randint(10,100,12)

In [15]:
arr4

array([18, 84, 37, 98, 89, 36, 85, 26, 44, 78, 31, 35])

In [16]:
np.max(arr4)

98

In [17]:
np.min(arr4)

18

In [18]:
np.mean(arr4)

55.083333333333336

In [19]:
np.median(arr4)

40.5

In [20]:
np.std(arr4)

27.78926151511687

In [21]:
np.var(arr4)

772.2430555555555

In [22]:
np.sin(arr4)

array([-0.75098725,  0.73319032, -0.64353813, -0.57338187,  0.86006941,
       -0.99177885, -0.17607562,  0.76255845,  0.01770193,  0.51397846,
       -0.40403765, -0.42818267])

In [23]:
np.cos(arr4)

array([ 0.66031671, -0.6800235 ,  0.76541405, -0.81928825,  0.51017704,
       -0.12796369, -0.98437664,  0.64691932,  0.99984331, -0.85780309,
        0.91474236, -0.90369221])

In [24]:
arr2

array([[ 2,  3,  6],
       [ 6,  8,  9],
       [12, 34, 56]])

In [25]:
arr2.shape

(3, 3)

In [26]:
arr2.size

9

In [27]:
arr1=np.array([23,56,12,89,8])

In [28]:
arr2=np.array([45,78,7,9,12])

In [29]:
arr1>arr2

array([False, False,  True,  True, False])

In [34]:
arr3=arr1[arr1>50]

In [35]:
arr3

array([56, 89])

In [37]:
arr5=np.array([3,6,np.nan,9,np.nan,89])

In [38]:
np.isnan(arr5)

array([False, False,  True, False,  True, False])

In [39]:
arr5[np.isnan(arr5)]

array([nan, nan])

In [40]:
[~np.isnan(arr5)]

[array([ True,  True, False,  True, False,  True])]

In [41]:
arr5[~np.isnan(arr5)]

array([ 3.,  6.,  9., 89.])

In [42]:
arr5=np.random.randint(10,100,15)

In [43]:
arr5

array([97, 97, 53, 80, 71, 35, 37, 69, 54, 96, 26, 16, 34, 84, 10])

In [44]:
arr5[arr5>50]

array([97, 97, 53, 80, 71, 69, 54, 96, 84])

In [45]:
arr5[~(arr5>50)]

array([35, 37, 26, 16, 34, 10])

In [47]:
#copy :
#shallow copy

arr6=arr5

In [48]:
arr6

array([97, 97, 53, 80, 71, 35, 37, 69, 54, 96, 26, 16, 34, 84, 10])

In [49]:
arr6[0]=1000

In [50]:
arr6

array([1000,   97,   53,   80,   71,   35,   37,   69,   54,   96,   26,
         16,   34,   84,   10])

In [51]:
arr5

array([1000,   97,   53,   80,   71,   35,   37,   69,   54,   96,   26,
         16,   34,   84,   10])

In [52]:
arr7=arr5.view()

In [53]:
arr7

array([1000,   97,   53,   80,   71,   35,   37,   69,   54,   96,   26,
         16,   34,   84,   10])

In [54]:
arr7[1]=2000

In [55]:
arr7

array([1000, 2000,   53,   80,   71,   35,   37,   69,   54,   96,   26,
         16,   34,   84,   10])

In [56]:
arr5

array([1000, 2000,   53,   80,   71,   35,   37,   69,   54,   96,   26,
         16,   34,   84,   10])

In [57]:
#deep copy

arr8=arr5.copy()


In [58]:
arr8

array([1000, 2000,   53,   80,   71,   35,   37,   69,   54,   96,   26,
         16,   34,   84,   10])

In [59]:
arr8[2]=3000

In [60]:
arr8

array([1000, 2000, 3000,   80,   71,   35,   37,   69,   54,   96,   26,
         16,   34,   84,   10])

In [61]:
arr5

array([1000, 2000,   53,   80,   71,   35,   37,   69,   54,   96,   26,
         16,   34,   84,   10])

In [63]:
#Transposing:

arr2=np.array([[34,56,78],[23,90,87]])

In [64]:
arr2

array([[34, 56, 78],
       [23, 90, 87]])

In [65]:
np.transpose(arr2)

array([[34, 23],
       [56, 90],
       [78, 87]])

In [66]:
arr2.T

array([[34, 23],
       [56, 90],
       [78, 87]])

In [68]:
arr3=np.random.randint(10,500,12)

In [69]:
arr3

array([253, 399, 448, 293, 494, 284, 411, 166, 387,  15, 230, 132])

In [71]:
arr3.reshape(3,4)

array([[253, 399, 448, 293],
       [494, 284, 411, 166],
       [387,  15, 230, 132]])

In [72]:
arr3.reshape(4,3)

array([[253, 399, 448],
       [293, 494, 284],
       [411, 166, 387],
       [ 15, 230, 132]])

In [73]:
arr3.reshape(2,2,3)

array([[[253, 399, 448],
        [293, 494, 284]],

       [[411, 166, 387],
        [ 15, 230, 132]]])

In [74]:
arr2

array([[34, 56, 78],
       [23, 90, 87]])

In [75]:
for x in arr2:
    print(x)

[34 56 78]
[23 90 87]


In [76]:
for x in arr2.flatten():
    print(x)

34
56
78
23
90
87


In [77]:
arr2.flatten()

array([34, 56, 78, 23, 90, 87])

In [78]:
#pandas

In [79]:
import pandas as pd

In [80]:
#1D : Series
#2D : DataFrame

In [81]:
A=[23,56,78,90]

In [82]:
arr1=np.array(A)

In [83]:
s1=pd.Series(A)

In [84]:
s1

0    23
1    56
2    78
3    90
dtype: int64

In [85]:
s1[2]

78

In [86]:
s2=pd.Series(A,index=['a','b','c','d'])

In [87]:
s2

a    23
b    56
c    78
d    90
dtype: int64

In [88]:
s4=pd.Series(np.random.randint(1,100,20))

In [90]:
np.max(s4)

93

In [91]:
s4.max()

93

In [92]:
np.mean(s4)

43.8

In [93]:
s4.mean()

43.8

In [94]:
s5=pd.Series([23,45,np.nan,89,32,np.nan])

In [95]:
s5.count()

4

In [96]:
s5.size

6

In [ ]:
#DataFrame

In [98]:
A=[10,45,67,89]

In [99]:
s=pd.Series(A)

In [100]:
s

0    10
1    45
2    67
3    89
dtype: int64

In [101]:
d=pd.DataFrame(A)

In [102]:
d

0
0  10
1  45
2  67
3  89

In [103]:
df1=pd.DataFrame([[12,34,56],[67,89,43],[22,67,89],[90,56,21]])

In [104]:
df1

0   1   2
0  12  34  56
1  67  89  43
2  22  67  89
3  90  56  21

In [105]:
df1=pd.DataFrame([[12,34,56],[67,89,43],[22,67,89],[90,56,21]],columns=['A','B','C'])

In [106]:
df1

A   B   C
0  12  34  56
1  67  89  43
2  22  67  89
3  90  56  21

In [108]:
x=df1['A']

In [110]:
df1[['A','B']]

A   B
0  12  34
1  67  89
2  22  67
3  90  56

In [111]:
df1

A   B   C
0  12  34  56
1  67  89  43
2  22  67  89
3  90  56  21

In [113]:
df1.loc[1]

A    67
B    89
C    43
Name: 1, dtype: int64

In [114]:
df1.loc[1:3] #till last index

A   B   C
1  67  89  43
2  22  67  89
3  90  56  21

In [115]:
df1.iloc[1:3] # end-1

A   B   C
1  67  89  43
2  22  67  89

In [116]:
df1

A   B   C
0  12  34  56
1  67  89  43
2  22  67  89
3  90  56  21

In [117]:
df1.iloc[1:3][['A','B']]

A   B
1  67  89
2  22  67

In [118]:
df1.iloc[2:][['B','C']]

B   C
2  67  89
3  56  21

In [119]:
df1['D']=df1['A']+df1['B']

In [121]:
df1

A   B   C    D
0  12  34  56   46
1  67  89  43  156
2  22  67  89   89
3  90  56  21  146

In [122]:
df=pd.read_csv("/Users/admin/Downloads/train.csv")

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [127]:
df.describe() #int,flaot

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [128]:
df.describe(include='all')

PassengerId    Survived      Pclass                   Name   Sex  \
count    891.000000  891.000000  891.000000                    891   891   
unique          NaN         NaN         NaN                    891     2   
top             NaN         NaN         NaN  Greenberg, Mr. Samuel  male   
freq            NaN         NaN         NaN                      1   577   
mean     446.000000    0.383838    2.308642                    NaN   NaN   
std      257.353842    0.486592    0.836071                    NaN   NaN   
min        1.000000    0.000000    1.000000                    NaN   NaN   
25%      223.500000    0.000000    2.000000                    NaN   NaN   
50%      446.000000    0.000000    3.000000                    NaN   NaN   
75%      668.500000    1.000000    3.000000                    NaN   NaN   
max      891.000000    1.000000    3.000000                    NaN   NaN   

               Age       SibSp       Parch    Ticket        Fare Cabin  \
count   714.000000  891.000000  891.000000       891  891.000000   204   
unique         NaN         NaN         NaN       681         NaN   147   
top            NaN         NaN         NaN  CA. 2343         NaN    G6   
freq           NaN         NaN         NaN         7         NaN     4   
mean     29.699118    0.523008    0.381594       NaN   32.204208   NaN   
std      14.526497    1.102743    0.806057       NaN   49.693429   NaN   
min       0.420000    0.000000    0.000000       NaN    0.000000   NaN   
25%      20.125000    0.000000    0.000000       NaN    7.910400   NaN   
50%      28.000000    0.000000    0.000000       NaN   14.454200   NaN   
75%      38.000000    1.000000    0.000000       NaN   31.000000   NaN   
max      80.000000    8.000000    6.000000       NaN  512.329200   NaN   

       Embarked  
count       889  
unique        3  
top           S  
freq        644  
mean        NaN  
std         NaN  
min         NaN  
25%         NaN  
50%         NaN  
75%         NaN  
max         NaN

In [129]:
df.head() #top 5

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [130]:
df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [131]:
df.tail() #last 5 

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [132]:
df.loc[5:7]

PassengerId  Survived  Pclass                            Name   Sex   Age  \
5            6         0       3                Moran, Mr. James  male   NaN   
6            7         0       1         McCarthy, Mr. Timothy J  male  54.0   
7            8         0       3  Palsson, Master. Gosta Leonard  male   2.0   

   SibSp  Parch  Ticket     Fare Cabin Embarked  
5      0      0  330877   8.4583   NaN        Q  
6      0      0   17463  51.8625   E46        S  
7      3      1  349909  21.0750   NaN        S

In [133]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [134]:
df[['Name','Age']]

Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [135]:
df1=df[df['Sex']=='male']

In [137]:
df[(df['Sex']=="male") & (df['Age']>40)]

PassengerId  Survived  Pclass                            Name   Sex  \
6              7         0       1         McCarthy, Mr. Timothy J  male   
33            34         0       2           Wheadon, Mr. Edward H  male   
35            36         0       1  Holverson, Mr. Alexander Oskar  male   
54            55         0       1  Ostby, Mr. Engelhart Cornelius  male   
62            63         0       1     Harris, Mr. Henry Birkhardt  male   
..           ...       ...     ...                             ...   ...   
845          846         0       3             Abbing, Mr. Anthony  male   
851          852         0       3             Svensson, Mr. Johan  male   
857          858         1       1          Daly, Mr. Peter Denis   male   
860          861         0       3         Hansen, Mr. Claus Peter  male   
873          874         0       3     Vander Cruyssen, Mr. Victor  male   

      Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
6    54.0      0      0       17463  51.8625   E46        S  
33   66.0      0      0  C.A. 24579  10.5000   NaN        S  
35   42.0      1      0      113789  52.0000   NaN        S  
54   65.0      0      1      113509  61.9792   B30        C  
62   45.0      1      0       36973  83.4750   C83        S  
..    ...    ...    ...         ...      ...   ...      ...  
845  42.0      0      0   C.A. 5547   7.5500   NaN        S  
851  74.0      0      0      347060   7.7750   NaN        S  
857  51.0      0      0      113055  26.5500   E17        S  
860  41.0      2      0      350026  14.1083   NaN        S  
873  47.0      0      0      345765   9.0000   NaN        S  

[102 rows x 12 columns]

In [138]:
df=pd.read_csv("/Users/admin/Downloads/train.csv",nrows=100)

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  100 non-null    int64  
 1   Survived     100 non-null    int64  
 2   Pclass       100 non-null    int64  
 3   Name         100 non-null    object 
 4   Sex          100 non-null    object 
 5   Age          78 non-null     float64
 6   SibSp        100 non-null    int64  
 7   Parch        100 non-null    int64  
 8   Ticket       100 non-null    object 
 9   Fare         100 non-null    float64
 10  Cabin        20 non-null     object 
 11  Embarked     99 non-null     object 
dtypes: float64(2), int64(5), object(5)
memory usage: 9.5+ KB


In [140]:
df=pd.read_csv("/Users/admin/Downloads/train.csv",usecols=['Name','Sex','Age'])

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    891 non-null    object 
 1   Sex     891 non-null    object 
 2   Age     714 non-null    float64
dtypes: float64(1), object(2)
memory usage: 21.0+ KB


In [142]:
df1=pd.read_csv("/Users/admin/Desktop/data.csv")

In [143]:
df1.head()

1  0  3         Braund, Mr. Owen Harris  male    22  1.1  0.1  A/5 21171  \
0   5  0  3        Allen, Mr. William Henry  male  35.0    0    0     373450   
1   6  0  3                Moran, Mr. James  male   NaN    0    0     330877   
2   7  0  1         McCarthy, Mr. Timothy J  male  54.0    0    0      17463   
3   8  0  3  Palsson, Master. Gosta Leonard  male   2.0    3    1     349909   
4  13  0  3  Saundercock, Mr. William Henry  male  20.0    0    0  A/5. 2151   

      7.25 Unnamed: 10  S  
0   8.0500         NaN  S  
1   8.4583         NaN  Q  
2  51.8625         E46  S  
3  21.0750         NaN  S  
4   8.0500         NaN  S

In [144]:
df1=pd.read_csv("/Users/admin/Desktop/data.csv",header=None)

In [145]:
df1.head()

0   1   2                               3     4     5   6   7          8   \
0   1   0   3         Braund, Mr. Owen Harris  male  22.0   1   0  A/5 21171   
1   5   0   3        Allen, Mr. William Henry  male  35.0   0   0     373450   
2   6   0   3                Moran, Mr. James  male   NaN   0   0     330877   
3   7   0   1         McCarthy, Mr. Timothy J  male  54.0   0   0      17463   
4   8   0   3  Palsson, Master. Gosta Leonard  male   2.0   3   1     349909   

        9    10 11  
0   7.2500  NaN  S  
1   8.0500  NaN  S  
2   8.4583  NaN  Q  
3  51.8625  E46  S  
4  21.0750  NaN  S

In [146]:
df1=pd.read_csv("/Users/admin/Desktop/data.csv",header=None,names=['a','b','c','d',
                                                                  'e','f','g','h',
                                                                  'i','j','k','L'])

In [147]:
df1.head()

a  b  c                               d     e     f  g  h          i  \
0  1  0  3         Braund, Mr. Owen Harris  male  22.0  1  0  A/5 21171   
1  5  0  3        Allen, Mr. William Henry  male  35.0  0  0     373450   
2  6  0  3                Moran, Mr. James  male   NaN  0  0     330877   
3  7  0  1         McCarthy, Mr. Timothy J  male  54.0  0  0      17463   
4  8  0  3  Palsson, Master. Gosta Leonard  male   2.0  3  1     349909   

         j    k  L  
0   7.2500  NaN  S  
1   8.0500  NaN  S  
2   8.4583  NaN  Q  
3  51.8625  E46  S  
4  21.0750  NaN  S

In [149]:
df2=pd.read_csv("/Users/admin/Downloads/Data science with Python 1 2/movies.dat",
               sep="::")

<ipython-input-149-9bb0779baea9>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df2=pd.read_csv("/Users/admin/Downloads/Data science with Python 1 2/movies.dat",


In [150]:
df2

1                    Toy Story (1995)   Animation|Children's|Comedy
0        2                      Jumanji (1995)  Adventure|Children's|Fantasy
1        3             Grumpier Old Men (1995)                Comedy|Romance
2        4            Waiting to Exhale (1995)                  Comedy|Drama
3        5  Father of the Bride Part II (1995)                        Comedy
4        6                         Heat (1995)         Action|Crime|Thriller
...    ...                                 ...                           ...
3877  3948             Meet the Parents (2000)                        Comedy
3878  3949          Requiem for a Dream (2000)                         Drama
3879  3950                    Tigerland (2000)                         Drama
3880  3951             Two Family House (2000)                         Drama
3881  3952               Contender, The (2000)                Drama|Thriller

[3882 rows x 3 columns]

Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
886                              Montvila, Rev. Juozas    male  27.0
887                       Graham, Miss. Margaret Edith  female  19.0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN
889                              Behr, Mr. Karl Howell    male  26.0
890                                Dooley, Mr. Patrick    male  32.0

[891 rows x 3 columns]

In [152]:
df1=pd.read_csv("/Users/admin/Downloads/train.csv",)

In [154]:
df1.shape

(891, 12)

In [158]:
list(df1.columns.values)

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [162]:
df1['Age'].isnull().sum()

177

In [163]:
df1.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [164]:
df1.dropna()

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [165]:
df1.dropna(how="all")

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [167]:
df1.dropna(subset=['Embarked'])

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[889 rows x 12 columns]

In [170]:
df1.dropna(inplace=True)

In [171]:
df1.shape

(183, 12)

In [172]:
df1=pd.read_csv("/Users/admin/Downloads/train.csv")

In [173]:
df1=df1.dropna()

In [174]:
df1.shape

(183, 12)

In [175]:
df1=pd.read_csv("/Users/admin/Downloads/train.csv")

In [177]:
df1.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [179]:
df1['Age'].fillna(df1['Age'].mean(),inplace=True)

In [180]:
df1.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [182]:
#df1.dropna(axis=1)
#df1.dropna(axis=1,how='all')

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket     Fare  
0        1      0         A/5 21171   7.2500  
1        1      0          PC 17599  71.2833  
2        0      0  STON/O2. 3101282   7.9250  
3        1      0            113803  53.1000  
4        0      0            373450   8.0500  
..     ...    ...               ...      ...  
886      0      0            211536  13.0000  
887      0      0            112053  30.0000  
888      1      2        W./C. 6607  23.4500  
889      0      0            111369  30.0000  
890      0      0            370376   7.7500  

[891 rows x 10 columns]