In [1]:
#webscraping :
# bs4 => BeautifulSoup

html_doc = """
<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>

<p class="story">...</p>
"""


In [2]:
from bs4 import BeautifulSoup

In [3]:
soup=BeautifulSoup(html_doc,'html.parser')

In [7]:
#print(soup.prettify())

In [8]:
soup.title

<title>The Dormouse's story</title>

In [9]:
soup.title.get_text()

"The Dormouse's story"

In [10]:
soup.p

<p class="title"><b>The Dormouse's story</b></p>

In [11]:
soup.p.b

<b>The Dormouse's story</b>

In [12]:
soup.p.b.get_text()

"The Dormouse's story"

In [13]:
soup.find_all('a') #list

[<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2">Lacie</a>,
 <a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>]

In [14]:
soup.find_all('p')

[<p class="title"><b>The Dormouse's story</b></p>,
 <p class="story">Once upon a time there were three little sisters; and their names were
 <a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
 <a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
 and they lived at the bottom of a well.</p>,
 <p class="story">...</p>]

In [15]:
soup.find_all('p','story')

[<p class="story">Once upon a time there were three little sisters; and their names were
 <a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
 <a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
 and they lived at the bottom of a well.</p>,
 <p class="story">...</p>]

In [16]:
soup.find('p','story')

<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>

In [19]:
soup.find(id='link2')

<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a>

In [20]:
import urllib.request

In [21]:
page=urllib.request.urlopen("https://en.wikipedia.org/wiki/List_of_state_and_union_territory_capitals_in_India")

In [22]:
page.status

200

In [24]:
soup=BeautifulSoup(page,'html.parser')

In [26]:
table=soup.find('table',"wikitable sortable plainrowheaders")

In [28]:
import pandas as pd

In [29]:
df=pd.read_html(str(table))

In [31]:
df[0]

No.              State   Administrative / Executive capital  \
0     1     Andhra Pradesh                     Visakhapatnam[3]   
1     2  Arunachal Pradesh                             Itanagar   
2     3              Assam                               Dispur   
3     4              Bihar                                Patna   
4     5       Chhattisgarh                      Naya Raipur [c]   
5     6                Goa                           Panaji [d]   
6     7            Gujarat                          Gandhinagar   
7     8            Haryana                           Chandigarh   
8     9   Himachal Pradesh                               Shimla   
9    10          Jharkhand                               Ranchi   
10   11          Karnataka                            Bengaluru   
11   12             Kerala                   Thiruvananthapuram   
12   13     Madhya Pradesh                               Bhopal   
13   14        Maharashtra                            Mumbai[e]   
14   15            Manipur                               Imphal   
15   16          Meghalaya                             Shillong   
16   17            Mizoram                               Aizawl   
17   18           Nagaland                               Kohima   
18   19             Odisha                          Bhubaneswar   
19   20             Punjab                           Chandigarh   
20   21          Rajasthan                               Jaipur   
21   22             Sikkim                           Gangtok[f]   
22   23         Tamil Nadu                           Chennai[g]   
23   24          Telangana                            Hyderabad   
24   25            Tripura                             Agartala   
25   26      Uttar Pradesh                              Lucknow   
26   27        Uttarakhand  Gairsain (summer) Dehradun (winter)   
27   28        West Bengal                              Kolkata   

                      Legislative capital Judicial capital  \
0                            Amaravati[3]       Kurnool[3]   
1                                Itanagar         Guwahati   
2                                  Dispur         Guwahati   
3                                   Patna            Patna   
4                                  Raipur         Bilaspur   
5                                Porvorim           Mumbai   
6                             Gandhinagar        Ahmedabad   
7                              Chandigarh       Chandigarh   
8   Shimla (Summer)Dharamsala (Winter)[6]           Shimla   
9                                  Ranchi           Ranchi   
10                              Bengaluru        Bengaluru   
11                     Thiruvananthapuram        Ernakulam   
12                                 Bhopal         Jabalpur   
13        Mumbai (Summer) Nagpur (Winter)           Mumbai   
14                                 Imphal           Imphal   
15                               Shillong         Shillong   
16                                 Aizawl         Guwahati   
17                                 Kohima         Guwahati   
18                            Bhubaneswar          Cuttack   
19                             Chandigarh       Chandigarh   
20                                 Jaipur          Jodhpur   
21                                Gangtok          Gangtok   
22                                Chennai          Chennai   
23                              Hyderabad        Hyderabad   
24                               Agartala         Agartala   
25                                Lucknow        Prayagraj   
26  Gairsain (summer)[8]Dehradun (winter)         Nainital   
27                                Kolkata          Kolkata   

    Year of establishment                                 Former capital  
0                    1956  Hyderabad[a](1956–2017) Amaravati (2017-2020)  
1                    1987                                              —  
2                    1972           

In [33]:
df[0].to_csv("/Users/admin/Movies/India.csv")

In [34]:
import requests

In [35]:
page=requests.get("http://forecast.weather.gov/MapClick.php?lat=37.7772&lon=-122.4168")

In [36]:
soup=BeautifulSoup(page.content,'html.parser')

In [42]:
seven_day=soup.find(id="seven-day-forecast-container")

In [43]:
seven_day

<div id="seven-day-forecast-container"><ul class="list-unstyled" id="seven-day-forecast-list"><li class="forecast-tombstone">
<div class="tombstone-container">
<p class="period-name">Today<br/><br/></p>
<p><img alt="Today: Partly sunny, with a high near 66. South southwest wind 5 to 10 mph increasing to 11 to 16 mph in the afternoon. Winds could gust as high as 21 mph. " class="forecast-icon" src="newimages/medium/bkn.png" title="Today: Partly sunny, with a high near 66. South southwest wind 5 to 10 mph increasing to 11 to 16 mph in the afternoon. Winds could gust as high as 21 mph. "/></p><p class="short-desc">Partly Sunny</p><p class="temp temp-high">High: 66 °F</p></div></li><li class="forecast-tombstone">
<div class="tombstone-container">
<p class="period-name">Tonight<br/><br/></p>
<p><img alt="Tonight: Rain.  Steady temperature around 59. Breezy, with a south southeast wind 13 to 22 mph, with gusts as high as 33 mph.  Chance of precipitation is 90%. New precipitation amounts betw

In [44]:
containers=seven_day.find_all('div',"tombstone-container")

In [46]:
containers[0]

<div class="tombstone-container">
<p class="period-name">Today<br/><br/></p>
<p><img alt="Today: Partly sunny, with a high near 66. South southwest wind 5 to 10 mph increasing to 11 to 16 mph in the afternoon. Winds could gust as high as 21 mph. " class="forecast-icon" src="newimages/medium/bkn.png" title="Today: Partly sunny, with a high near 66. South southwest wind 5 to 10 mph increasing to 11 to 16 mph in the afternoon. Winds could gust as high as 21 mph. "/></p><p class="short-desc">Partly Sunny</p><p class="temp temp-high">High: 66 °F</p></div>

In [48]:
containers[0].find('p',"period-name").get_text()

'Today'

In [49]:
containers[0].find('p',"short-desc").get_text()

'Partly Sunny'

In [50]:
containers[0].find('p',"temp").get_text()

'High: 66 °F'

In [52]:
containers[0].find('img')['title']

'Today: Partly sunny, with a high near 66. South southwest wind 5 to 10 mph increasing to 11 to 16 mph in the afternoon. Winds could gust as high as 21 mph. '

In [53]:
periods=[]
short_desc=[]
temp=[]
desc=[]

In [54]:
for x in range(len(containers)):
    periods.append(containers[x].find('p',"period-name").get_text())
    short_desc.append(containers[x].find('p',"short-desc").get_text())
    temp.append(containers[x].find('p',"temp").get_text())
    desc.append(containers[x].find('img')['title'])

In [57]:
weather=pd.DataFrame({'Periods':periods,'short_dsc':short_desc,
                     'Temp':temp,'Desc':desc})

In [58]:
weather

Periods                     short_dsc         Temp  \
0           Today                  Partly Sunny  High: 66 °F   
1         Tonight                Rain andBreezy   Low: 59 °F   
2       Wednesday                          Rain  High: 66 °F   
3  WednesdayNight                          Rain   Low: 59 °F   
4        Thursday                          Rain  High: 68 °F   
5   ThursdayNight                          Rain   Low: 58 °F   
6          Friday          Rain thenChance Rain  High: 64 °F   
7     FridayNight  Slight ChanceRain thenCloudy   Low: 53 °F   
8        Saturday                   Chance Rain  High: 63 °F   

                                                Desc  
0  Today: Partly sunny, with a high near 66. Sout...  
1  Tonight: Rain.  Steady temperature around 59. ...  
2  Wednesday: Rain.  High near 66. South wind 16 ...  
3  Wednesday Night: Rain.  Low around 59. South s...  
4  Thursday: Rain.  High near 68. South southwest...  
5  Thursday Night: Rain.  Low around 58. Chance o...  
6  Friday: Rain, mainly before 11am.  High near 6...  
7  Friday Night: A slight chance of rain before 1...  
8  Saturday: A chance of rain after 11am.  Mostly...

In [60]:
weather.to_csv("/Users/admin/Movies/weather.csv",index=False)

In [61]:
#Numpy :

len(temp)

9

In [62]:
len(short_desc)

9

In [65]:
#Numpy :
import numpy as np

A=[1,2,3,4]
B=[1.0,0.5,0.7,1.4]

In [ ]:
#arr_name=np.array(list)


In [66]:
arr1=np.array(A)

In [67]:
arr2=np.array(B)

In [69]:
#print(type(arr1))

<class 'numpy.ndarray'>


In [70]:
arr1*arr2

array([1. , 1. , 2.1, 5.6])

In [71]:
arr3=np.array([2,5,6])

In [73]:
#arr1*arr3

In [74]:
#1D array

arr1=np.array([2,4,6,89,12])

In [75]:
arr1.ndim

1

In [76]:
arr1.shape

(5,)

In [77]:
arr1[3]

89

In [79]:
arr1[-1:-3:-1]

array([12, 89])

In [80]:
#2D array

arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [81]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
arr2.ndim

2

In [83]:
arr2.shape

(3, 3)

In [84]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [85]:
arr3.shape

(4, 3)

In [86]:
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [88]:
arr3[2][1]

8

In [91]:
arr3[3,2]

12

In [95]:
arr3[2:,1]

array([ 8, 11])

In [97]:
arr3[2:,1:]

array([[ 8,  9],
       [11, 12]])

In [99]:
arr3[1:3,:2]

array([[4, 5],
       [7, 8]])

In [101]:
#3D array:
arr4=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])

In [102]:
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [103]:
arr4.ndim

3

In [104]:
arr4.shape

(3, 3, 3)

In [108]:
arr4[1,2,2]

18

In [109]:
arr4[2,1:3,2]

array([24, 27])

In [110]:
arr4[0:,1:,1]

array([[ 5,  8],
       [14, 17],
       [23, 26]])

In [111]:
#np.arange(start,end,step) 

In [112]:
arr7=np.arange(1,10,0.2)

In [113]:
arr7

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [116]:
#np.linspace(start,end,number of item)
arr8=np.linspace(1,10,4)

In [117]:
arr8

array([ 1.,  4.,  7., 10.])

In [120]:
np.random.randint(1,100,5)

array([66, 15, 49, 42,  2])

In [124]:
np.random.rand(2,3,4) #0-1

array([[[0.56886117, 0.26765915, 0.16876816, 0.13510744],
        [0.97541275, 0.78543705, 0.83003476, 0.89113142],
        [0.85343907, 0.49601824, 0.48122818, 0.15551798]],

       [[0.7699641 , 0.22466176, 0.43556464, 0.8329577 ],
        [0.97382733, 0.63229741, 0.23946316, 0.17015616],
        [0.95158944, 0.09461986, 0.52524318, 0.45894736]]])

In [126]:
np.random.randn(3,4)

array([[ 0.68325839,  0.32181284,  2.65261415, -1.69377304],
       [ 0.35466078,  0.94394563, -0.44392707, -0.08736103],
       [-1.03356878, -1.39356487,  0.03710549,  0.7439025 ]])

In [127]:
np.random.uniform(1,100,5) #float

array([60.75741185, 79.14832607, 87.77833316, 74.94999143, 31.13661745])

In [128]:
#Broadcasting:


arr1=np.array([2,4,5,7])
arr2=np.array([5,6,7])

In [129]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [130]:
arr3=np.array([5,7,9,1])

In [131]:
arr1+arr3

array([ 7, 11, 14,  8])

In [132]:
arr3*3

array([15, 21, 27,  3])